### ISSUE TITLE
Description of Testing on the GAICD dataset.

### ISSUE THREAD

**Issue by geraltFromRivia** [lld533/Grid-Anchor-based-Image-Cropping-Pytorch#1]
Hello!

Thank you very much for sharing the code and dataset with the community. I have a questions about how would one go about testing previously published methods on the GAICD. I was wondering if you could possibly describe how do you test the VFN / VEN models on the GAICD dataset. Do you feed take the precomputed crops and then feed them each into the VFN / VEN and then rank order the crop scores?

Thank you very much.

**Comment by lld533** [comment]
> Hello!
> Thank you very much for sharing the code and dataset with the community. I have a questions about how would one go about testing previously published methods on the GAICD. I was wondering if you could possibly describe how do you test the VFN / VEN models on the GAICD dataset. Do you feed take the precomputed crops and then feed them each into the VFN / VEN and then rank order the crop scores?
> Thank you very much.

Thanks for your interest in our work. 

A quick answer to your question: yes, we precomputed crops of a test image and feed those crops into VFN/VEN model. I'm not pretty clear about ranking the scores and that part could be a little different. We will check the code and release more details to you soon.

**Comment by geraltFromRivia** [comment]
Thank you very much for your quick response.

**Comment by lld533** [comment]
> Thank you very much for your quick response.

Please check the "misc" folder of this repo, an example to test FEV models.

Usage:
1. Check out the repos of FEV from github. 
2. Unzip the stuff in the zip file to the the same directory of demo.py
3. Crops your test images and organize them as follows:
ROOT_DIR/
  img_name1/
    crop1.jpg
    crop2.jpg
    ...
  img_name2/
    crop1.jpg
    crop2.jpg
    ...
3. Open demo_b16.py and update the root directory of your pre-cropped images.
4. Run demo_b16.py. Check "aspect_ratio.sh" for your reference.
5. The script generates a text file to save the scores of the image crops.
6. Play with the scores and have fun.

**Comment by geraltFromRivia** [comment]
Thank you very much for your help!
