### ISSUE TITLE
set up issue

### ISSUE THREAD

**Issue by jygan** [lld533/Grid-Anchor-based-Image-Cropping-Pytorch#5]
can you share more about how to set up environment. which version of g++ you installed.
I got error

In file included from rod_align_kernel.cu:2:0:
rod_align_kernel.h:4:21: fatal error: THC/THC.h: No such file or directory

thanks

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# '/usr/local/lib/python3.5/dist-packages/torch/__init__.py'

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# /usr/local/lib/python3.5/dist-packages/torch/__init__.py

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# /usr/local/lib/python3.5/dist-packages/torch/__init__.py

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# /usr/local/lib/python3.5/dist-packages/torch/__init__.py

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# /usr/local/lib/python3.5/dist-packages/torch/__init__.py

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# /usr/local/lib/python3.5/dist-packages/torch/__init__.py

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by lld533** [comment]
It seems that the pytorch include directory is not included in the project for compilation.

In case of my environment, THC/THC.h is located at /usr/local/lib/python3.5/dist-packages/torch/include/THC/THC.h

I used gcc 5.4.0 for compilation. And I installed pytorch 1.1 through pip3 wheel (e.g. pip3 install torch torchvision). I'm not clear about conda installation. To find your pytorch installation path, try to execute the script after launch your python. 

#/usr/bin/python3
import torch
print(torch.__file__)
# /usr/local/lib/python3.5/dist-packages/torch/__init__.py

Try to export /path/to/pytorch/include/directory/ (for example, /usr/local/lib/python3.5/dist-packages/torch/include) if "THC/THC.h" is not found. Of course, you may seek help in pytorch forum. Good luck:)

**Comment by jygan** [comment]
thanks for help. i can build code now, my GPU machine use cuda 9.2, i also changed CUDA_HOME to right location, but when run TrainModel.py got error about looking for libcudart.so.10.0, why rod_align_api still try to use cuda 10.0, is there any cuda 10 api we used in rod_align_api? thanks a lot.

  File "TrainModel.py", line 1, in <module>
    from croppingModel import build_crop_model
  File "/home/user/project/Grid-Anchor-based-Image-Cropping-Pytorch/croppingModel.py", line 5, in <module>
    from rod_align.modules.rod_align import RoDAlignAvg, RoDAlign
  File "/home/user/project/Grid-Anchor-based-Image-Cropping-Pytorch/rod_align/modules/rod_align.py", line 3, in <module>
    from ..functions.rod_align import RoDAlignFunction
  File "/home/user/project/Grid-Anchor-based-Image-Cropping-Pytorch/rod_align/functions/rod_align.py", line 3, in <module>
    import rod_align_api
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by lld533** [comment]
> thanks for help. i can build code now, my GPU machine use cuda 9.2, i also changed CUDA_HOME to right location, but when run TrainModel.py got error about looking for libcudart.so.10.0, why rod_align_api still try to use cuda 10.0, is there any cuda 10 api we used in rod_align_api? thanks a lot.
> 
> File "TrainModel.py", line 1, in
> from croppingModel import build_crop_model
> File "/home/user/project/Grid-Anchor-based-Image-Cropping-Pytorch/croppingModel.py", line 5, in
> from rod_align.modules.rod_align import RoDAlignAvg, RoDAlign
> File "/home/user/project/Grid-Anchor-based-Image-Cropping-Pytorch/rod_align/modules/rod_align.py", line 3, in
> from ..functions.rod_align import RoDAlignFunction
> File "/home/user/project/Grid-Anchor-based-Image-Cropping-Pytorch/rod_align/functions/rod_align.py", line 3, in
> import rod_align_api
> ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

I don‘t deliberately call any cuda-10 exclusive code in roi/rod align source code. Starting from the official code compatible to pytorch-0.4, I updated some interface functions by following the instructions of pytorch cuda_extension or cpp-extension, so that both api packages are compatible with pytorch 1.0+.

CUDA-10 is required in my environment for 2 main reasons:
1/ My workstation is equipped with 2 TITAN RTX, which requires CUDA-10 and nvidia driver 430 or later at that time. Of course, with CUDA-9.2, my gpu card can still run well. It's still recommended to embrace cuda-10.0+.
2/ I installed PyTorch 1.1 or 1.2 via pip3 installation. The pre-built wheel was compiled with CUDA-10.0. This drives me to export CUDA-10 package to my env.

Regarding to your case, please double check whether you installed pytorch through pip and it is compiled with CUDA-10. If so, please export CUDA-10 to your own env and I believe the issue can be solved then. Good lock:)

**Comment by lifengheng** [comment]
@jygan Hello, I encounter the same problem : "fatal error: THC/THC.h: No such file or directory". Could you explain more specifically how you solved the problem? Thanks.

**Comment by cherryolg** [comment]
Hi, how did you solve this problem? I have the same problem! Looking forward to your reply!
`Compiling rod_align kernels by nvcc...
In file included from rod_align_kernel.cu:2:0:
rod_align_kernel.h:4:21: fatal error: THC/THC.h: No such file or directory
`
